### ISSUE TITLE
Action for MISS_HIT fails on pull request: `miss_hit.cfg: error: config file contains errors`

### ISSUE THREAD

**Issue by jsheunis** [jsheunis/fMRwhy#27]
The job fails for both the quality and style checking actions:

Here's the error report:

```
Run mh_metric --ci
miss_hit.cfg: error: config file contains errors
In miss_hit.cfg, line 8
| exclude_dir: "lib"
|              ^^^^^ error: does not exist
.: error: cannot find project root because the config file contains errors: please add a config file with the 'project_root' directive
MISS_HIT Metric Summary: 2 file(s) analysed, 3 error(s)
Error: Process completed with exit code 1.
```

@Remi-Gau is the `lib` directory perhaps a remnant from the use of this config in the `CPP_SPM` repo?

**Comment by jsheunis** [comment]
Should we also ignore:
- assets
- dependencies
- docs
- img
?

**Comment by Remi-Gau** [comment]
> @Remi-Gau is the `lib` directory perhaps a remnant from the use of this config in the `CPP_SPM` repo?

yup you are correct!!

Only ignore fodlers with `.m` files in them: so only `dependencies` as far I can see.
